"""Static world content for the medieval fantasy simulator."""

from __future__ import annotations

from fantasy_mmorpg.models import EnemyTemplate, Item, NPC, Quest, Recipe, Zone


FACTIONS = {
    "Hearthfolk": "Village families, innkeepers, hunters, and farmers.",
    "Crownwardens": "Soldiers loyal to the fractured crown.",
    "Silver Chapel": "Priests, healers, and relic keepers.",
    "Thornbound Circle": "Druids, witches, and old forest spirits.",
    "Black Banner": "Bandits, smugglers, and mercenary deserters.",
    "Ashen Covenant": "Dragon cultists seeking a new age of fire.",
    "Old Kingdom": "Ghosts and remnants of the fallen realm of Caer Velis.",
}


CLASS_TEMPLATES = {
    "knight": {
        "ancestry": "human",
        "background": "oath-sworn retainer",
        "attributes": {"strength": 8, "dexterity": 4, "intelligence": 3, "endurance": 8, "charisma": 5},
        "hp": 36,
        "mana": 6,
        "gold": 18,
        "items": {"rusted_longsword": 1, "leather_jerkin": 1, "travel_ration": 2, "healing_draught": 1},
    },
    "ranger": {
        "ancestry": "half-elf",
        "background": "border scout",
        "attributes": {"strength": 5, "dexterity": 8, "intelligence": 4, "endurance": 6, "charisma": 4},
        "hp": 28,
        "mana": 8,
        "gold": 14,
        "items": {"hunting_bow": 1, "leather_jerkin": 1, "travel_ration": 2, "healing_draught": 1},
    },
    "mage": {
        "ancestry": "highborn elf",
        "background": "academy exile",
        "attributes": {"strength": 2, "dexterity": 5, "intelligence": 9, "endurance": 4, "charisma": 6},
        "hp": 22,
        "mana": 26,
        "gold": 20,
        "items": {"ashwood_staff": 1, "apprentice_robe": 1, "mana_tonic": 2, "healing_draught": 1},
    },
    "cleric": {
        "ancestry": "dwarf",
        "background": "chapel mendicant",
        "attributes": {"strength": 5, "dexterity": 3, "intelligence": 6, "endurance": 7, "charisma": 7},
        "hp": 30,
        "mana": 20,
        "gold": 12,
        "items": {"iron_mace": 1, "pilgrim_charm": 1, "travel_ration": 1, "healing_draught": 2},
    },
    "rogue": {
        "ancestry": "halfling",
        "background": "locksmith of poor reputation",
        "attributes": {"strength": 4, "dexterity": 9, "intelligence": 6, "endurance": 4, "charisma": 5},
        "hp": 24,
        "mana": 10,
        "gold": 24,
        "items": {"balanced_dagger": 1, "shadow_cloak": 1, "smoke_bomb": 1, "healing_draught": 1},
    },
    "commoner": {
        "ancestry": "human",
        "background": "farmhand with impossible luck",
        "attributes": {"strength": 5, "dexterity": 5, "intelligence": 5, "endurance": 5, "charisma": 5},
        "hp": 26,
        "mana": 10,
        "gold": 8,
        "items": {"woodcutters_axe": 1, "travel_ration": 3, "healing_draught": 1},
    },
}


ITEMS = {
    "rusted_longsword": Item(
        "rusted_longsword",
        "Rusted Longsword",
        "weapon",
        "A veteran blade with more memory than shine.",
        14,
        stats={"attack": 4},
        equip_slot="weapon",
        tags=("blade", "iron"),
    ),
    "hunting_bow": Item(
        "hunting_bow",
        "Hunting Bow",
        "weapon",
        "A yew bow used by wardens and poachers alike.",
        16,
        stats={"attack": 3, "speed": 2},
        equip_slot="weapon",
        tags=("bow", "wood"),
    ),
    "ashwood_staff": Item(
        "ashwood_staff",
        "Ashwood Staff",
        "weapon",
        "Warm runes crawl beneath the bark when moonlight touches it.",
        18,
        rarity="uncommon",
        stats={"attack": 2, "mana": 6},
        equip_slot="weapon",
        tags=("focus", "wood"),
    ),
    "iron_mace": Item(
        "iron_mace",
        "Iron Mace",
        "weapon",
        "A chapel weapon meant to break bone without drawing blood.",
        15,
        stats={"attack": 4},
        equip_slot="weapon",
        tags=("blunt", "iron"),
    ),
    "balanced_dagger": Item(
        "balanced_dagger",
        "Balanced Dagger",
        "weapon",
        "A narrow blade that disappears neatly up a sleeve.",
        18,
        stats={"attack": 3, "speed": 3},
        equip_slot="weapon",
        tags=("blade", "finesse"),
    ),
    "woodcutters_axe": Item(
        "woodcutters_axe",
        "Woodcutter's Axe",
        "weapon",
        "Heavy, honest, and terrifying in desperate hands.",
        10,
        stats={"attack": 3},
        equip_slot="weapon",
        tags=("axe", "tool"),
    ),
    "leather_jerkin": Item(
        "leather_jerkin",
        "Leather Jerkin",
        "armor",
        "Boiled leather patched with old militia colors.",
        12,
        stats={"defense": 2, "max_hp": 3},
        equip_slot="armor",
    ),
    "apprentice_robe": Item(
        "apprentice_robe",
        "Apprentice Robe",
        "armor",
        "Ink-stained sleeves hide pockets for chalk, charms, and panic.",
        13,
        stats={"defense": 1, "mana": 5},
        equip_slot="armor",
    ),
    "shadow_cloak": Item(
        "shadow_cloak",
        "Shadow Cloak",
        "armor",
        "Dark cloth with a hood cut for vanishing in tavern corners.",
        20,
        rarity="uncommon",
        stats={"defense": 1, "speed": 3},
        equip_slot="armor",
    ),
    "pilgrim_charm": Item(
        "pilgrim_charm",
        "Pilgrim Charm",
        "trinket",
        "A silver sunburst wrapped in blue thread.",
        16,
        stats={"mana": 4, "defense": 1},
        equip_slot="trinket",
    ),
    "warden_shield": Item(
        "warden_shield",
        "Crownwarden Shield",
        "shield",
        "Oak, iron, and a lion sigil scarred by arrowheads.",
        28,
        rarity="uncommon",
        stats={"defense": 4, "max_hp": 4},
        equip_slot="offhand",
    ),
    "goblin_spear": Item(
        "goblin_spear",
        "Goblin Spear",
        "weapon",
        "Short, ugly, and wickedly practical.",
        13,
        stats={"attack": 3, "speed": 1},
        equip_slot="weapon",
        tags=("spear", "iron"),
    ),
    "chapel_relic": Item(
        "chapel_relic",
        "Silver Chapel Relic",
        "quest",
        "A cracked reliquary humming with a psalm no living choir remembers.",
        80,
        rarity="rare",
        tags=("relic", "silver"),
    ),
    "courier_satchel": Item(
        "courier_satchel",
        "Sealed Courier Satchel",
        "quest",
        "A wax-sealed dispatch bag bearing the Crownwarden lion.",
        45,
        rarity="uncommon",
    ),
    "moonleaf": Item(
        "moonleaf",
        "Moonleaf",
        "material",
        "A pale herb that opens its veins only under clouded light.",
        4,
        tags=("herb", "alchemy"),
    ),
    "marshroot": Item(
        "marshroot",
        "Marshroot",
        "material",
        "Bitter roots prized by healers and swamp witches.",
        5,
        tags=("herb", "alchemy"),
    ),
    "wolf_pelt": Item(
        "wolf_pelt",
        "Wolf Pelt",
        "material",
        "Coarse fur that still smells of pine sap and rain.",
        6,
        tags=("hide", "leather"),
    ),
    "iron_ore": Item(
        "iron_ore",
        "Iron Ore",
        "material",
        "Dark stone veined with forge promise.",
        6,
        tags=("ore", "metal"),
    ),
    "bone_dust": Item(
        "bone_dust",
        "Bone Dust",
        "material",
        "Fine grey powder gathered from restless graves.",
        7,
        tags=("necromancy", "alchemy"),
    ),
    "silver_shard": Item(
        "silver_shard",
        "Silver Shard",
        "material",
        "A sliver of moon-bright metal cold enough to numb skin.",
        15,
        rarity="uncommon",
        tags=("silver", "metal"),
    ),
    "dragon_ash": Item(
        "dragon_ash",
        "Dragon Ash",
        "material",
        "Black ash that glitters like embers when lied to.",
        40,
        rarity="rare",
        tags=("dragon", "alchemy"),
    ),
    "healing_draught": Item(
        "healing_draught",
        "Healing Draught",
        "potion",
        "A red glass vial of honeyed herbs and chapel alcohol.",
        12,
        effects={"heal": 18},
        tags=("potion",),
    ),
    "greater_healing_draught": Item(
        "greater_healing_draught",
        "Greater Healing Draught",
        "potion",
        "A dense crimson tonic that knits wounds while it burns.",
        32,
        rarity="uncommon",
        effects={"heal": 40},
        tags=("potion",),
    ),
    "mana_tonic": Item(
        "mana_tonic",
        "Mana Tonic",
        "potion",
        "Blue liquor distilled from moonleaf and bad decisions.",
        14,
        effects={"mana": 16},
        tags=("potion",),
    ),
    "travel_ration": Item(
        "travel_ration",
        "Travel Ration",
        "food",
        "Hard bread, smoked cheese, and a strip of peppered goat.",
        3,
        effects={"heal": 5},
        tags=("food",),
    ),
    "smoke_bomb": Item(
        "smoke_bomb",
        "Smoke Bomb",
        "tool",
        "A clay shell packed with soot, saltpeter, and rogue confidence.",
        18,
        effects={"flee": 60},
        tags=("tool",),
    ),
    "sunfire_scroll": Item(
        "sunfire_scroll",
        "Sunfire Scroll",
        "scroll",
        "A single-use chapel prayer that bites like noon.",
        35,
        rarity="uncommon",
        effects={"damage": 32},
        tags=("scroll", "holy"),
    ),
    "bandit_token": Item(
        "bandit_token",
        "Black Banner Token",
        "quest",
        "A bent copper coin cut with a black pennant mark.",
        8,
        tags=("token",),
    ),
    "ancient_tablet": Item(
        "ancient_tablet",
        "Ancient War Tablet",
        "lore",
        "A broken tablet naming kings erased from every legal chronicle.",
        60,
        rarity="rare",
        tags=("relic", "lore"),
    ),
    "wyvern_scale": Item(
        "wyvern_scale",
        "Wyvern Scale",
        "material",
        "Green-black scale plates hard enough to ruin a file.",
        22,
        rarity="uncommon",
        tags=("scale", "leather"),
    ),
}


ENEMIES = {
    "cellar_rat": EnemyTemplate(
        "cellar_rat",
        "Cellar Rat",
        "A knee-high rat fattened on spilled ale and bad magic.",
        1,
        10,
        3,
        0,
        9,
        "Beasts",
        loot_table=(("travel_ration", 0.15),),
    ),
    "grey_wolf": EnemyTemplate(
        "grey_wolf",
        "Grey Wolf",
        "A lean pack hunter with frost around its muzzle.",
        2,
        18,
        6,
        1,
        18,
        "Beasts",
        loot_table=(("wolf_pelt", 0.75),),
        abilities=("bleeding bite",),
    ),
    "road_bandit": EnemyTemplate(
        "road_bandit",
        "Road Bandit",
        "A hungry deserter wearing stolen crown colors inside out.",
        2,
        20,
        7,
        2,
        22,
        "Black Banner",
        loot_table=(("bandit_token", 0.85), ("healing_draught", 0.15)),
        abilities=("dirty trick",),
        opening_line="The bandit twirls a notched knife. 'Toll road now. Pay in coin or teeth.'",
    ),
    "goblin_skirmisher": EnemyTemplate(
        "goblin_skirmisher",
        "Goblin Skirmisher",
        "A yellow-eyed raider with a stolen spear and too many bells.",
        3,
        24,
        8,
        2,
        32,
        "Black Banner",
        loot_table=(("goblin_spear", 0.25), ("iron_ore", 0.25)),
    ),
    "restless_bones": EnemyTemplate(
        "restless_bones",
        "Restless Bones",
        "A skeleton held together by grave-cold blue sparks.",
        3,
        26,
        8,
        3,
        34,
        "Old Kingdom",
        loot_table=(("bone_dust", 0.7), ("silver_shard", 0.15)),
        abilities=("rattle curse",),
    ),
    "marsh_wight": EnemyTemplate(
        "marsh_wight",
        "Marsh Wight",
        "A drowned oathbreaker with reeds tangled through its ribs.",
        4,
        34,
        10,
        4,
        48,
        "Old Kingdom",
        loot_table=(("bone_dust", 0.8), ("marshroot", 0.3)),
        abilities=("drain warmth",),
    ),
    "ashen_cultist": EnemyTemplate(
        "ashen_cultist",
        "Ashen Cultist",
        "A masked zealot whose prayers smell of smoke.",
        5,
        40,
        12,
        4,
        64,
        "Ashen Covenant",
        loot_table=(("dragon_ash", 0.25), ("sunfire_scroll", 0.1)),
        abilities=("ember hex",),
    ),
    "troll_marauder": EnemyTemplate(
        "troll_marauder",
        "Troll Marauder",
        "A slab-shouldered brute wearing a wagon wheel as a necklace.",
        6,
        58,
        15,
        6,
        92,
        "Beasts",
        loot_table=(("iron_ore", 0.5), ("greater_healing_draught", 0.1)),
        abilities=("regenerate",),
    ),
    "wyvern_hatchling": EnemyTemplate(
        "wyvern_hatchling",
        "Wyvern Hatchling",
        "A shrieking young drake with smoke leaking between its teeth.",
        7,
        68,
        18,
        7,
        120,
        "Ashen Covenant",
        loot_table=(("wyvern_scale", 0.7), ("dragon_ash", 0.4)),
        abilities=("venom sting", "wing buffet"),
    ),
    "ember_drake": EnemyTemplate(
        "ember_drake",
        "Ember Drake",
        "A young dragon crouched in volcanic glass, each breath a furnace door.",
        9,
        110,
        25,
        10,
        250,
        "Ashen Covenant",
        loot_table=(("dragon_ash", 1.0), ("wyvern_scale", 1.0)),
        abilities=("flame surge", "tail sweep", "terror roar"),
    ),
}


ZONES = {
    "eldermist_village": Zone(
        "eldermist_village",
        "Eldermist Village",
        "settlement",
        "Thatched roofs crouch behind a palisade of ashwood stakes. Smoke, wet wool, and nervous hope fill the square.",
        0,
        exits={"north": "blackpine_woods", "east": "barrow_road", "south": "sunken_chapel"},
        npc_ids=("mira", "brother_ansem", "tomas", "old_maeve"),
        shop_ids=("mira", "brother_ansem"),
        resources=("travel_ration",),
        secrets=("village_well_cache",),
        faction="Hearthfolk",
        ambience=("A bell rings twice, then stops as if ashamed.", "Children argue over whether dragons cast shadows."),
        rest_allowed=True,
    ),
    "barrow_road": Zone(
        "barrow_road",
        "The Barrow Road",
        "road",
        "Ancient burial mounds line the trade road, their standing stones carved with names no priest will translate.",
        1,
        exits={"west": "eldermist_village", "east": "ironbell_keep", "north": "ruined_watchtower"},
        npc_ids=("courier_pavel",),
        encounters=(("road_bandit", 6), ("grey_wolf", 4)),
        resources=("moonleaf", "iron_ore"),
        secrets=("courier_wreck",),
        faction="Crownwardens",
        ambience=("Crows hop from milestone to milestone.", "Old coins glint in wagon ruts after rain."),
    ),
    "blackpine_woods": Zone(
        "blackpine_woods",
        "Blackpine Woods",
        "wilderness",
        "Pines grow close enough to whisper secrets into one another. Mushrooms shine like watchful eyes beneath the needles.",
        2,
        exits={"south": "eldermist_village", "east": "ruined_watchtower", "north": "brackenmarsh"},
        npc_ids=("serel", "witch_ygraine"),
        encounters=(("grey_wolf", 5), ("road_bandit", 2), ("goblin_skirmisher", 3)),
        resources=("moonleaf", "wolf_pelt"),
        secrets=("thornbound_grove",),
        faction="Thornbound Circle",
        ambience=("A fox watches you with almost human disappointment.", "Sap drips black from a wounded pine."),
    ),
    "ruined_watchtower": Zone(
        "ruined_watchtower",
        "Ruined Watchtower",
        "dungeon",
        "The old tower leans like a drunk knight. Goblin smoke leaks from arrow slits above collapsed Crownwarden banners.",
        3,
        exits={"south": "barrow_road", "west": "blackpine_woods", "down": "old_kingdom_catacombs"},
        npc_ids=("captain_rowan",),
        encounters=(("goblin_skirmisher", 7), ("road_bandit", 2), ("restless_bones", 1)),
        resources=("iron_ore",),
        secrets=("watchtower_armory",),
        faction="Crownwardens",
        ambience=("Something small laughs from behind a fallen stair.", "The wind hums through broken murder holes."),
    ),
    "brackenmarsh": Zone(
        "brackenmarsh",
        "Brackenmarsh",
        "swamp",
        "Black water mirrors a colorless sky. Every hummock may be a path, a grave, or a thing pretending to be either.",
        4,
        exits={"south": "blackpine_woods", "east": "sunken_chapel", "north": "ashenfang_mountains"},
        npc_ids=("fenna",),
        encounters=(("marsh_wight", 5), ("restless_bones", 3), ("grey_wolf", 2)),
        resources=("marshroot", "bone_dust"),
        secrets=("drowned_oathstone",),
        faction="Old Kingdom",
        ambience=("Bubbles rise where nothing moved.", "A lantern flickers far out where no road runs."),
    ),
    "sunken_chapel": Zone(
        "sunken_chapel",
        "Sunken Chapel",
        "dungeon",
        "Half the chapel has slid into marsh water. Silver saints stare from cracked windows with accusing faces.",
        4,
        exits={"north": "eldermist_village", "west": "brackenmarsh", "down": "crypt_of_lanterns"},
        npc_ids=("sister_calia",),
        encounters=(("restless_bones", 5), ("marsh_wight", 3), ("ashen_cultist", 2)),
        resources=("silver_shard", "bone_dust"),
        secrets=("defiled_altar",),
        faction="Silver Chapel",
        ambience=("A hymn echoes one note behind your heartbeat.", "Holy water beads on stone, then crawls uphill."),
        rest_allowed=True,
    ),
    "ironbell_keep": Zone(
        "ironbell_keep",
        "Ironbell Keep",
        "fortress",
        "A square keep of black stone guards the valley road. Its bell is cracked, but every soldier still salutes the silence.",
        2,
        exits={"west": "barrow_road", "north": "ashenfang_mountains"},
        npc_ids=("lord_eldric", "quartermaster_vehn", "captain_rowan"),
        shop_ids=("quartermaster_vehn",),
        resources=("iron_ore",),
        secrets=("keep_cipher"),
        faction="Crownwardens",
        ambience=("Pages hurry past with dispatches tied in red cord.", "The cracked bell moves though no one pulls the rope."),
        rest_allowed=True,
    ),
    "old_kingdom_catacombs": Zone(
        "old_kingdom_catacombs",
        "Old Kingdom Catacombs",
        "dungeon",
        "Beneath the tower, royal dead sleep behind bronze doors etched with crimes rewritten as victories.",
        5,
        exits={"up": "ruined_watchtower", "east": "crypt_of_lanterns"},
        npc_ids=("velis_spirit",),
        encounters=(("restless_bones", 4), ("marsh_wight", 4), ("ashen_cultist", 2)),
        resources=("bone_dust", "silver_shard"),
        secrets=("ancient_tablet_cache",),
        faction="Old Kingdom",
        ambience=("Dust gathers into footprints before your own arrive.", "A crownless skull turns slightly as you pass."),
    ),
    "crypt_of_lanterns": Zone(
        "crypt_of_lanterns",
        "Crypt of Lanterns",
        "dungeon",
        "Blue lanterns float above open sarcophagi, each flame fed by an unfinished confession.",
        6,
        exits={"up": "sunken_chapel", "west": "old_kingdom_catacombs", "north": "dragonwake_crater"},
        encounters=(("marsh_wight", 5), ("ashen_cultist", 3), ("troll_marauder", 1)),
        resources=("silver_shard", "bone_dust"),
        secrets=("lantern_king_oath"),
        faction="Old Kingdom",
        ambience=("Every flame leans away from your shadow.", "A name you do not know forms on your tongue."),
    ),
    "ashenfang_mountains": Zone(
        "ashenfang_mountains",
        "Ashenfang Mountains",
        "mountains",
        "Jagged peaks pierce low clouds. Charred pine trunks point toward a crater that glows after sunset.",
        6,
        exits={"south": "ironbell_keep", "west": "brackenmarsh", "east": "dragonwake_crater"},
        npc_ids=("kael_the_exile",),
        encounters=(("troll_marauder", 5), ("wyvern_hatchling", 4), ("ashen_cultist", 3)),
        resources=("iron_ore", "dragon_ash", "wyvern_scale"),
        secrets=("exile_camp",),
        faction="Ashen Covenant",
        ambience=("Ash falls upward for a breath, then remembers itself.", "Something vast moves under the mountain."),
    ),
    "dragonwake_crater": Zone(
        "dragonwake_crater",
        "Dragonwake Crater",
        "endgame",
        "A wound in the world smolders here. Obsidian ribs curve around a lake of red light and broken prophecies.",
        9,
        exits={"west": "ashenfang_mountains", "south": "crypt_of_lanterns"},
        npc_ids=("ash_oracle",),
        encounters=(("wyvern_hatchling", 5), ("ashen_cultist", 5), ("ember_drake", 1)),
        resources=("dragon_ash", "wyvern_scale"),
        secrets=("dragon_oath_fragment",),
        faction="Ashen Covenant",
        ambience=("The crater breathes in time with distant wings.", "Your shadow points toward the fire no matter where you stand."),
    ),
}


NPCS = {
    "mira": NPC(
        "mira",
        "Mira",
        "Innkeeper of the Fogbound Stag",
        "Hearthfolk",
        "warm, practical, and impossible to surprise",
        "If you have coin, I have stew. If you have courage, I have worse work.",
        {
            "work": "Rats below the Stag are too clever for cats. Clear them and I will feed you like a baron.",
            "rumors": "The Barrow Road eats couriers. Not kills, mind you. Eats. Boots, satchels, names, all gone.",
            "village": "Eldermist survives by keeping its gates shut and its gossip sharper than knives.",
            "bandits": "Black Banner deserters buy ale with Crownwarden coin and leave with village sons.",
        },
        quest_ids=("rats_in_the_cellar",),
        shop_inventory=("travel_ration", "healing_draught", "smoke_bomb"),
        services=("rest", "rumors"),
    ),
    "brother_ansem": NPC(
        "brother_ansem",
        "Brother Ansem",
        "Silver Chapel Healer",
        "Silver Chapel",
        "gentle, exhausted, and stubbornly hopeful",
        "The saints keep ledgers too, friend. Let yours show mercy where it can.",
        {
            "healing": "Bring moonleaf and marshroot, and I can make miracles fit inside cheap glass.",
            "chapel": "Our southern chapel drowned in mud and old sin. Something there sings backward.",
            "undead": "Restless dead rise when promises are broken. Ask who profited from the breaking.",
            "relic": "The reliquary beneath the Sunken Chapel must not fall to the Ashen Covenant.",
        },
        quest_ids=("herbs_for_the_healer", "a_shrine_defiled"),
        shop_inventory=("healing_draught", "mana_tonic", "sunfire_scroll"),
        services=("heal", "blessing"),
    ),
    "tomas": NPC(
        "tomas",
        "Tomas",
        "Militia Boy",
        "Hearthfolk",
        "brave in public and terrified in detail",
        "I am on watch. Proper watch. Not hiding behind a spear taller than me.",
        {
            "goblins": "They ring bells on their spears so the dark can applaud them.",
            "training": "Captain Rowan says fear is useful if you point it outward.",
            "village": "I know every loose board in the palisade. Do not tell Mira.",
            "dragons": "My aunt saw a shadow cross the moon. It had horns.",
        },
    ),
    "old_maeve": NPC(
        "old_maeve",
        "Old Maeve",
        "Village Seer",
        "Thornbound Circle",
        "cryptic, amused, and older than she admits",
        "Ah, the road has brought me another question wearing boots.",
        {
            "fate": "Fate is a river. Sensible folk build bridges. Heroes jump in wearing armor.",
            "old kingdom": "Caer Velis did not fall. It was buried alive by its own oaths.",
            "dragon": "The crater is not where the dragon landed. It is where the world flinched.",
            "secrets": "Wells remember more than priests. Drop patience, not coins.",
        },
    ),
    "courier_pavel": NPC(
        "courier_pavel",
        "Pavel",
        "Missing Courier",
        "Crownwardens",
        "injured, loyal, and very thirsty",
        "Keep your voice low. The road has ears, and some wear knives.",
        {
            "satchel": "I hid the dispatch when the ambush started. If Rowan gets it, the keep may stand.",
            "ambush": "Black Banner knew my route. Someone in Ironbell is selling roads.",
            "road": "Never camp beside a barrow. The dead are polite until bandits wake them.",
        },
        quest_ids=("the_missing_courier",),
    ),
    "serel": NPC(
        "serel",
        "Serel",
        "Blackpine Hunter",
        "Hearthfolk",
        "watchful, dry, and kinder to wolves than nobles",
        "Step where I step unless you fancy explaining your death to the moss.",
        {
            "wolves": "The wolves are hungry because goblins drove deer east. Kill one problem and another howls.",
            "woods": "Blackpine listens. Speak plainly and do not promise what you cannot bury.",
            "bandits": "Bandits fear hunger more than law. That makes them dangerous and recruitable.",
        },
        quest_ids=("bandits_at_the_old_mill",),
    ),
    "witch_ygraine": NPC(
        "witch_ygraine",
        "Ygraine",
        "Thornbound Witch",
        "Thornbound Circle",
        "acerbic, ancient, and fond of exact prices",
        "Do not touch the mushrooms. They are debating whether you are edible.",
        {
            "magic": "Magic is debt. Wizards hide the bill under nicer handwriting.",
            "circle": "The Thornbound remember when the crown begged trees for permission.",
            "marsh": "The marsh keeps oathbreakers. Bring marshroot if you want medicine, bring lies if you want ghosts.",
            "dragon": "Dragon ash can wake seeds that should stay asleep.",
        },
        shop_inventory=("mana_tonic", "smoke_bomb", "greater_healing_draught"),
        services=("identify", "crafting"),
    ),
    "captain_rowan": NPC(
        "captain_rowan",
        "Captain Rowan",
        "Crownwarden Commander",
        "Crownwardens",
        "stern, honorable, and running out of soldiers",
        "Report quickly. Every delay becomes a grave with my name on the paperwork.",
        {
            "goblins": "The watchtower must be retaken. If goblins hold the ridge, Ironbell starves.",
            "courier": "Pavel carried troop movements. Without his satchel, I am blind by royal decree.",
            "keep": "Ironbell is a locked fist. Good for war, poor for trust.",
            "traitor": "Someone sells our routes. I need proof before I hang suspicion.",
        },
        quest_ids=("the_missing_courier", "the_goblin_banner"),
    ),
    "quartermaster_vehn": NPC(
        "quartermaster_vehn",
        "Vehn",
        "Keep Quartermaster",
        "Crownwardens",
        "efficient, suspicious, and allergic to heroics",
        "If you break it, buy it. If you bleed on it, buy two.",
        {
            "trade": "War is logistics wearing a sword. Remember that before you ask for discounts.",
            "weapons": "Iron from Ashenfang holds an edge if the smith survives fetching it.",
            "bandits": "Black Banner gear passes through too many honest hands. That worries me.",
        },
        shop_inventory=("rusted_longsword", "warden_shield", "healing_draught", "sunfire_scroll"),
        services=("repair", "trade"),
    ),
    "lord_eldric": NPC(
        "lord_eldric",
        "Lord Eldric",
        "Warden of Ironbell",
        "Crownwardens",
        "polished, political, and harder than he smiles",
        "Adventurers are expensive, but cheaper than armies. Convince me you are the former.",
        {
            "crown": "The crown is a candle in wind. I shield it because darkness is worse.",
            "old kingdom": "Dead kingdoms are useful warnings until fools start taking instruction.",
            "dragon": "If the crater wakes, titles will matter less than walls.",
            "traitor": "Speak carefully. Accusations in a keep echo into nooses.",
        },
    ),
    "sister_calia": NPC(
        "sister_calia",
        "Sister Calia",
        "Lantern Nun",
        "Silver Chapel",
        "haunted, serene, and fearless around the dead",
        "Do not fear the dead. Fear the living who taught them unfinished business.",
        {
            "chapel": "The altar was opened from below. That is not desecration; it is excavation.",
            "lanterns": "Blue lanterns guide confessions to rest. Red flame guides hunger.",
            "relic": "Find the reliquary before the cult grinds it into dragon ash.",
            "undead": "Name them if you can. A named ghost remembers how to sleep.",
        },
        quest_ids=("a_shrine_defiled",),
    ),
    "fenna": NPC(
        "fenna",
        "Fenna",
        "Marsh Ferryman",
        "Hearthfolk",
        "laconic, practical, and unimpressed by rank",
        "Boat goes where coin points. Marsh goes where it wants.",
        {
            "marsh": "Step on grass, not shine. Shine is water. Water is teeth.",
            "ghosts": "Ghosts are folk who forgot the fare. Happens.",
            "chapel": "Nuns sing there at night. Not living ones, usually.",
        },
    ),
    "velis_spirit": NPC(
        "velis_spirit",
        "Aurelian",
        "Memory of Caer Velis",
        "Old Kingdom",
        "regal, remorseful, and fraying at the edges",
        "Who enters our guilt with warm blood?",
        {
            "old kingdom": "We chained a dragon beneath vows, then called the chain peace.",
            "war": "The crown above stole victory from the dead below. Both debts remain unpaid.",
            "tablet": "Bring the war tablet into daylight, and lies will begin to rot.",
            "dragon": "Do not slay hunger with hunger. Bind fire with truth or flee it.",
        },
        quest_ids=("ashes_of_the_old_war",),
    ),
    "kael_the_exile": NPC(
        "kael_the_exile",
        "Kael",
        "Ashen Exile",
        "Ashen Covenant",
        "bitter, wounded, and not yet beyond saving",
        "If you came to kill cultists, start elsewhere. I resigned before the screaming got musical.",
        {
            "cult": "The Ashen Covenant promises rebirth. They omit how much burning happens first.",
            "crater": "The oracle feeds names to the fire. Give yours and it will answer in someone else's voice.",
            "dragon": "The drake is only a herald. The true sleeper dreams under the glass.",
            "redemption": "Bring proof the chapel relic survives, and I may remember how to pray.",
        },
        quest_ids=("the_dragons_wake",),
    ),
    "ash_oracle": NPC(
        "ash_oracle",
        "The Ash Oracle",
        "Voice in the Cinders",
        "Ashen Covenant",
        "ecstatic, inhuman, and dangerously persuasive",
        "Kneel, little ember. The old world is dry enough to burn.",
        {
            "fire": "Fire is honest. It makes every hidden thing confess its shape.",
            "dragon": "Our mother stirs. Her wingbeat will flatten law, hunger, grief, and choice.",
            "covenant": "We are not cult. We are weather.",
            "surrender": "Lay down your name. Rise as smoke. Be everywhere.",
        },
    ),
}


QUESTS = {
    "rats_in_the_cellar": Quest(
        "rats_in_the_cellar",
        "Rats in the Cellar",
        "mira",
        "Mira needs the unnaturally bold rats beneath the Fogbound Stag cleared out.",
        objectives=({"type": "kill", "target": "cellar_rat", "count": 3},),
        rewards={"gold": 18, "xp": 35, "items": {"travel_ration": 2}, "reputation": {"Hearthfolk": 2}},
        completion_text="Mira wipes her hands on her apron. 'Good. If they start wearing helmets next week, I am blaming you.'",
        faction="Hearthfolk",
    ),
    "herbs_for_the_healer": Quest(
        "herbs_for_the_healer",
        "Herbs for the Healer",
        "brother_ansem",
        "Brother Ansem can brew medicine if supplied with moonleaf and marshroot.",
        objectives=(
            {"type": "collect", "target": "moonleaf", "count": 3},
            {"type": "collect", "target": "marshroot", "count": 1},
        ),
        rewards={"gold": 16, "xp": 45, "items": {"healing_draught": 3}, "reputation": {"Silver Chapel": 3}},
        completion_text="Ansem seals three red vials. 'May these buy you time enough to choose mercy.'",
        faction="Silver Chapel",
    ),
    "the_missing_courier": Quest(
        "the_missing_courier",
        "The Missing Courier",
        "captain_rowan",
        "Captain Rowan needs Pavel's sealed satchel recovered before Ironbell's enemies read it.",
        objectives=(
            {"type": "talk", "target": "courier_pavel", "count": 1},
            {"type": "collect", "target": "courier_satchel", "count": 1},
        ),
        rewards={"gold": 35, "xp": 70, "items": {"warden_shield": 1}, "reputation": {"Crownwardens": 4}},
        completion_text="Rowan breaks the seal, reads, and goes pale. 'You did not save a letter. You saved a wall.'",
        faction="Crownwardens",
        required_level=2,
    ),
    "bandits_at_the_old_mill": Quest(
        "bandits_at_the_old_mill",
        "Bandits at the Old Mill",
        "serel",
        "Serel wants proof that the Black Banner deserters preying on the woods have been scattered.",
        objectives=({"type": "collect", "target": "bandit_token", "count": 3},),
        rewards={"gold": 28, "xp": 60, "items": {"smoke_bomb": 2}, "reputation": {"Hearthfolk": 2, "Black Banner": -3}},
        completion_text="Serel counts the tokens without smiling. 'Good. Fewer hungry knives between here and winter.'",
        faction="Hearthfolk",
        required_level=2,
    ),
    "the_goblin_banner": Quest(
        "the_goblin_banner",
        "The Goblin Banner",
        "captain_rowan",
        "Retake the ruined watchtower by breaking the goblin skirmishers holding its upper floors.",
        objectives=({"type": "kill", "target": "goblin_skirmisher", "count": 4},),
        rewards={"gold": 42, "xp": 95, "items": {"goblin_spear": 1}, "reputation": {"Crownwardens": 4}},
        completion_text="Rowan plants a fresh banner in the mud. 'Ugly ground, but ours again.'",
        faction="Crownwardens",
        required_level=3,
    ),
    "a_shrine_defiled": Quest(
        "a_shrine_defiled",
        "A Shrine Defiled",
        "sister_calia",
        "Recover the Silver Chapel relic from the drowned sanctuary before the Ashen Covenant claims it.",
        objectives=(
            {"type": "explore", "target": "sunken_chapel", "count": 1},
            {"type": "collect", "target": "chapel_relic", "count": 1},
        ),
        rewards={"gold": 38, "xp": 110, "items": {"sunfire_scroll": 2}, "reputation": {"Silver Chapel": 5, "Ashen Covenant": -2}},
        completion_text="Calia kisses the reliquary and weeps once, silently. The blue lanterns steady.",
        faction="Silver Chapel",
        required_level=3,
    ),
    "ashes_of_the_old_war": Quest(
        "ashes_of_the_old_war",
        "Ashes of the Old War",
        "velis_spirit",
        "The spirit Aurelian asks that a buried war tablet be brought into the living world.",
        objectives=({"type": "collect", "target": "ancient_tablet", "count": 1},),
        rewards={"gold": 25, "xp": 125, "items": {"silver_shard": 2}, "reputation": {"Old Kingdom": 5, "Crownwardens": -1}},
        completion_text="The spirit bows like a collapsing statue. 'Truth is not mercy, but it is a door.'",
        faction="Old Kingdom",
        required_level=4,
    ),
    "the_dragons_wake": Quest(
        "the_dragons_wake",
        "The Dragon's Wake",
        "kael_the_exile",
        "Kael believes the Ash Oracle can be delayed if its drake herald is slain and dragon ash gathered.",
        objectives=(
            {"type": "kill", "target": "ember_drake", "count": 1},
            {"type": "collect", "target": "dragon_ash", "count": 3},
        ),
        rewards={"gold": 100, "xp": 300, "items": {"greater_healing_draught": 3}, "reputation": {"Ashen Covenant": -8, "Crownwardens": 3, "Silver Chapel": 3}},
        completion_text="Kael looks toward the crater. 'That bought us a breath. Spend it better than my order did.'",
        faction="Ashen Covenant",
        required_level=6,
    ),
}


RECIPES = {
    "healing_draught": Recipe(
        "healing_draught",
        "Healing Draught",
        {"moonleaf": 2, "travel_ration": 1},
        "healing_draught",
    ),
    "greater_healing_draught": Recipe(
        "greater_healing_draught",
        "Greater Healing Draught",
        {"healing_draught": 2, "marshroot": 2},
        "greater_healing_draught",
    ),
    "mana_tonic": Recipe(
        "mana_tonic",
        "Mana Tonic",
        {"moonleaf": 2, "silver_shard": 1},
        "mana_tonic",
    ),
    "smoke_bomb": Recipe(
        "smoke_bomb",
        "Smoke Bomb",
        {"bone_dust": 1, "iron_ore": 1},
        "smoke_bomb",
    ),
    "sunfire_scroll": Recipe(
        "sunfire_scroll",
        "Sunfire Scroll",
        {"silver_shard": 1, "dragon_ash": 1},
        "sunfire_scroll",
    ),
}


SECRET_DEFINITIONS = {
    "village_well_cache": {
        "text": "A loose stone inside the village well hides a dry pouch and a child's map of wolf trails.",
        "items": {"healing_draught": 1, "moonleaf": 1},
        "lore": "The well predates Eldermist and is lined with Old Kingdom stone.",
    },
    "courier_wreck": {
        "text": "Broken wagon spokes mark Pavel's ambush site. The sealed satchel is wedged under a barrow stone.",
        "items": {"courier_satchel": 1},
        "lore": "The bandits left Crownwarden bootprints but no Crownwarden dead.",
    },
    "thornbound_grove": {
        "text": "You find a ring of stones where antlers hang from red thread. Moonleaf grows thick in the center.",
        "items": {"moonleaf": 3},
        "lore": "The Thornbound Circle traded prophecy for blood here during the last succession war.",
    },
    "watchtower_armory": {
        "text": "Behind a fallen rack, a Crownwarden shield remains wrapped in oilcloth.",
        "items": {"warden_shield": 1, "iron_ore": 2},
        "lore": "The watchtower fell from betrayal inside the signal room.",
    },
    "drowned_oathstone": {
        "text": "A submerged oathstone bears names that glow when spoken. One belongs to Lord Eldric's house.",
        "items": {"marshroot": 2, "bone_dust": 1},
        "lore": "Crown nobles swore to bury Caer Velis and keep its dragon-chain secret.",
    },
    "defiled_altar": {
        "text": "Under the split altar lies the reliquary, wrapped in wet velvet and claw marks.",
        "items": {"chapel_relic": 1, "silver_shard": 1},
        "lore": "The Ashen Covenant tried to grind the relic into ash but could not break the saint's seal.",
    },
    "keep_cipher": {
        "text": "A cipher sheet hidden behind the quartermaster's ledger lists altered patrol routes.",
        "items": {"bandit_token": 1},
        "lore": "Someone in Ironbell sold safe roads to the Black Banner.",
    },
    "ancient_tablet_cache": {
        "text": "A bronze door opens to reveal a war tablet laid across a king's empty coffin.",
        "items": {"ancient_tablet": 1, "silver_shard": 1},
        "lore": "Caer Velis bound a dragon beneath the crater and called the wound a victory.",
    },
    "lantern_king_oath": {
        "text": "The blue lanterns arrange themselves into a crown, then scatter as if ashamed.",
        "items": {"sunfire_scroll": 1, "bone_dust": 2},
        "lore": "The Lantern King broke the dragon-chain to save his heir, dooming the valley by inches.",
    },
    "exile_camp": {
        "text": "Kael's abandoned camp contains burned covenant masks and a map of vents beneath the crater.",
        "items": {"dragon_ash": 1, "greater_healing_draught": 1},
        "lore": "The Ash Oracle is not one person, but a chorus speaking through whoever inhales the crater smoke.",
    },
    "dragon_oath_fragment": {
        "text": "Obsidian glass preserves a fragment of an oath: 'Wake only when kings forget hunger.'",
        "items": {"dragon_ash": 2, "wyvern_scale": 1},
        "lore": "The sleeping dragon was once a guardian, not a tyrant.",
    },
}


RANDOM_EVENTS = (
    {
        "id": "caravan_arrival",
        "name": "Merchant Caravan",
        "text": "A bell-hung caravan reaches the valley, bringing news, silk, and three contradictory maps.",
        "duration": 4,
        "reputation": {"Hearthfolk": 1},
    },
    {
        "id": "barrow_mist",
        "name": "Barrow Mist",
        "text": "Pale mist spills from the barrows. Undead stir more boldly until dawn.",
        "duration": 5,
        "reputation": {"Old Kingdom": 1},
    },
    {
        "id": "black_banner_raid",
        "name": "Black Banner Raid",
        "text": "Smoke rises from the road. The Black Banner is raiding supply carts near Ironbell.",
        "duration": 5,
        "reputation": {"Black Banner": -1, "Crownwardens": 1},
    },
    {
        "id": "dragon_shadow",
        "name": "Dragon Shadow",
        "text": "A horned shadow crosses the sun. Even the priests stop pretending it was a cloud.",
        "duration": 3,
        "reputation": {"Ashen Covenant": 1},
    },
)
